/**
 * Generates packages/plugin-validation/src/safetySnapshot.ts from the
 * canonical safety-kernel sources in apps/web/src/lib/safety/.
 *
 * Why a snapshot: CLAUDE.md invariant 1 says safety rules live in
 * apps/web/src/lib/safety/. The marketplace can't import from apps/web,
 * so we mirror just the data it needs (no helpers, no DB types).
 *
 * Run: `pnpm gen:safety-snapshot` (from repo root) or
 *      `pnpm -F @cropcard/plugin-validation gen:safety-snapshot`.
 *
 * CI gates on drift via `git diff --exit-code packages/plugin-validation/src/safetySnapshot.ts`.
 */

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  CROP_FAMILIES,
  CHEMISTRY_KILL_MATRIX,
  type ChemistryProfile
} from '../../../apps/web/src/lib/safety/cropFamilyLethality.ts';
import { CHEMISTRY_CLASSES } from '../../../apps/web/src/lib/safety/types.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'src', 'safetySnapshot.ts');

const IDENTIFIER = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

function keyOf(name: string): string {
  return IDENTIFIER.test(name) ? name : `'${name}'`;
}

function literalArray(name: string, values: readonly string[]): string {
  const items = values.map((v) => `  '${v}'`).join(',\n');
  return `export const ${name} = [\n${items}\n] as const;`;
}

function familyArray(families: ReadonlyArray<string>): string {
  return '[' + families.map((f) => `'${f}'`).join(', ') + ']';
}

function serializeMatrix(matrix: Readonly<Record<string, ChemistryProfile>>): string {
  const entries = Object.entries(matrix).map(([cls, profile]) => {
    const notes = JSON.stringify(profile.notes);
    return `  ${keyOf(cls)}: {
    hracGroup: ${profile.hracGroup},
    killsFamilies: ${familyArray(profile.killsFamilies)},
    notes: ${notes}
  }`;
  });
  return `export const CHEMISTRY_KILL_MATRIX: Readonly<Record<ChemistryClass, ChemistryProfile>> = {
${entries.join(',\n')}
};`;
}

const header = `/**
 * AUTO-GENERATED by packages/plugin-validation/scripts/gen-snapshot.ts.
 * Do NOT edit by hand — run \`pnpm gen:safety-snapshot\` from the repo root.
 *
 * Source files (canonical, per CLAUDE.md invariant 1):
 *   apps/web/src/lib/safety/cropFamilyLethality.ts
 *   apps/web/src/lib/safety/types.ts
 *
 * Only the data needed by Zod schemas + bypassCheck is mirrored here;
 * kernel helpers (killedFamilies, hracGroupOf, etc.) stay in apps/web.
 */
`;

const types = `export type ChemistryClass = (typeof CHEMISTRY_CLASSES)[number];
export type CropFamily = (typeof CROP_FAMILIES)[number];

export interface ChemistryProfile {
  killsFamilies: ReadonlyArray<CropFamily>;
  notes: string;
  /** HRAC global mode-of-action group number. */
  hracGroup: number;
}`;

const body = [
  header,
  literalArray('CHEMISTRY_CLASSES', CHEMISTRY_CLASSES),
  '',
  literalArray('CROP_FAMILIES', CROP_FAMILIES),
  '',
  types,
  '',
  serializeMatrix(CHEMISTRY_KILL_MATRIX),
  ''
].join('\n');

writeFileSync(OUT, body, 'utf8');
console.log(`wrote ${OUT} (${body.length} bytes)`);
