/**
 * GET /api/spray/records/export.csv
 *
 * Streams a CSV of the full spray-record set for compliance retention
 * (FR-09, NFR-05). Columns: id, occurredAt, blockId, blockName, sprayerId,
 * sprayerName, products, chemistry classes, conditions, rules version,
 * plugin hashes, locked.
 *
 * B-04 (Sprint D' close) additions:
 *   T1 — `blockName` column alongside `blockId` (Dale shouldn't have to
 *        cross-reference IDs against another sheet to identify a row).
 *   T2 — `sprayerName` column alongside `sprayerId`.
 *   T9 — exporter-signature trailing row ("Generated by CropCard v{X}
 *        on {ISO date} · exported by {email}") so the source of an
 *        export is unambiguous.
 */

import { type RequestHandler } from '@sveltejs/kit';
import papa from 'papaparse';

import { evaluateLock, listSprayEvents } from '$lib/db/sprayEvents';
import { listBlocks } from '$lib/db/blocks';
import { listSprayers } from '$lib/db/sprayers';
import { requireUser } from '$lib/server/auth';
import { APP_VERSION } from '$lib/version';

export const GET: RequestHandler = (event) => {
  const user = requireUser(event);
  const sprayerId = event.url.searchParams.get('sprayerId') ?? undefined;
  const blockId = event.url.searchParams.get('blockId') ?? undefined;
  const events = listSprayEvents({ limit: 10_000, sprayerId, blockId });

  // T1 / T2 — id → name lookups.
  const blockNameById = new Map(
    listBlocks().map((b) => [b.id, b.blockLabel ?? b.name])
  );
  const sprayerNameById = new Map(listSprayers().map((s) => [s.id, s.label]));

  const rows = events.map((e) => ({
    id: e.id,
    occurredAtIso: new Date(e.occurredAt).toISOString(),
    blockId: e.blockId,
    blockName: blockNameById.get(e.blockId) ?? '(unknown block)',
    sprayerId: e.sprayerId,
    sprayerName: sprayerNameById.get(e.sprayerId) ?? '(unknown sprayer)',
    performedById: e.performedById,
    products: e.products.map((p) => p.pluginId).join('|'),
    chemistryClasses: Array.from(new Set(e.products.flatMap((p) => p.chemistryClasses))).join('|'),
    windMph: e.conditions.windMph,
    tempF: e.conditions.tempF,
    rainForecastMmNext24h: e.conditions.rainForecastMmNext24h,
    rulesVersion: e.rulesVersion,
    pluginHashes: Object.entries(e.pluginHashes)
      .map(([id, h]) => `${id}:${h.slice(0, 16)}`)
      .join('|'),
    customRateOverride: e.customRateOverride ? 'true' : 'false',
    locked: evaluateLock(e) ? 'true' : 'false'
  }));

  const csvBody = papa.unparse(rows, { header: true });

  // T9 — exporter signature appended as a final row. Column 1 carries the
  // metadata so spreadsheet apps render it visibly without disturbing the
  // header-on-row-1 convention. Stays out of the data rows so consumers
  // doing strict CSV ingest can simply drop the last row.
  const generatedAt = new Date().toISOString();
  const signatureLine = `# Generated by CropCard v${APP_VERSION} on ${generatedAt} · exported by ${user.email}`;
  const csv = `${csvBody}\n${signatureLine}\n`;
  const stamp = generatedAt.slice(0, 19).replace(/[:T]/g, '-');

  return new Response(csv, {
    headers: {
      'Content-Type': 'text/csv; charset=utf-8',
      'Content-Disposition': `attachment; filename="cropcard-spray-records-${stamp}.csv"`,
      'X-CropCard-Generator': `CropCard/${APP_VERSION}`,
      'X-CropCard-Exported-By': user.email
    }
  });
};
