/**
 * GET /api/spray/records/export.csv
 *
 * Streams a CSV of the full spray-record set for compliance retention
 * (FR-09, NFR-05). Columns: id, occurredAt, blockId, blockName, sprayerId,
 * sprayerName, products, chemistry classes, conditions, rules version,
 * plugin hashes, locked.
 *
 * B-04 (Sprint D' close) additions:
 *   T1 — `blockName` column alongside `blockId` (Dale shouldn't have to
 *        cross-reference IDs against another sheet to identify a row).
 *   T2 — `sprayerName` column alongside `sprayerId`.
 *   T9 — exporter-signature trailing row ("Generated by CropCard v{X}
 *        on {ISO date} · exported by {email}") so the source of an
 *        export is unambiguous.
 *
 * Phase 32G (G2-07, G2-08) appends `record_kind` (application | hay),
 * `crop_commodity`, `moisture_pct`, `recorded_late` (yes | no | blank when
 * the kind does not track it) and `days_after_date`.
 */

import { type RequestHandler } from '@sveltejs/kit';
import papa from 'papaparse';

import { evaluateLock, listSprayEvents } from '$lib/db/sprayEvents';
import { listBlocks } from '$lib/db/blocks';
import { listSprayers } from '$lib/db/sprayers';
import { requireUser } from '$lib/server/auth';
import { parseExportDateRange } from '$lib/exports/dateRange';
import { localStamp, zoneCaption } from '$lib/exports/localTime';
import { prefsFor } from '$lib/db/userProfile';
import { APP_VERSION } from '$lib/version';
import { identityLabel } from '$lib/identity';
import { LOCK_WINDOW_MS } from '$lib/db/recordKinds';
import { getRegistry } from '$lib/server/registry';
import { listHayForExport } from '$lib/records/hayExport.server';
import { lateCells, UNTRACKED_LATE_CELLS } from '$lib/records/lateLabel';

export const GET: RequestHandler = async (event) => {
  const user = requireUser(event);
  const prefs = prefsFor(user.id);
  const sprayerId = event.url.searchParams.get('sprayerId') ?? undefined;
  const blockId = event.url.searchParams.get('blockId') ?? undefined;
  const { fromMs, toMs } = parseExportDateRange(event.url.searchParams, prefs);
  const events = listSprayEvents({ limit: 10_000, sprayerId, blockId, fromMs, toMs });

  // T1 / T2 — id → name lookups.
  const blockNameById = new Map(listBlocks().map((b) => [b.id, b.blockLabel ?? b.name]));
  const sprayerNameById = new Map(listSprayers().map((s) => [s.id, s.label]));

  const rows: Array<Record<string, string | number>> = events.map((e) => ({
    id: e.id,
    occurredAtIso: new Date(e.occurredAt).toISOString(),
    occurredAtLocal: localStamp(e.occurredAt, prefs),
    blockId: e.blockId,
    blockName: blockNameById.get(e.blockId) ?? '(unknown block)',
    sprayerId: e.sprayerId,
    sprayerName: sprayerNameById.get(e.sprayerId) ?? '(unknown sprayer)',
    performedById: e.performedById,
    products: e.products.map((p) => p.pluginId).join('|'),
    chemistryClasses: Array.from(new Set(e.products.flatMap((p) => p.chemistryClasses))).join('|'),
    windMph: e.conditions.windMph,
    tempF: e.conditions.tempF,
    rainForecastMmNext24h: e.conditions.rainForecastMmNext24h,
    // #320 / CT-S5-003 — attributability. Distinguishes operator-measured
    // readings from synthetic defaults so drift documentation is honest.
    conditionsProvenance: e.conditions.conditionsProvenance ?? 'default',
    rulesVersion: e.rulesVersion,
    pluginHashes: Object.entries(e.pluginHashes)
      .map(([id, h]) => `${id}:${h.slice(0, 16)}`)
      .join('|'),
    customRateOverride: e.customRateOverride ? 'true' : 'false',
    locked: evaluateLock(e) ? 'true' : 'false',
    record_kind: 'application',
    crop_commodity: '',
    moisture_pct: '',
    ...UNTRACKED_LATE_CELLS
  }));

  // G2-07: hay cuttings ride along as `record_kind = hay` rows (a sprayer
  // filter leaves them out). Every column added after #326 is appended, so
  // existing importers keep their positions.
  if (!sprayerId) {
    const registry = await getRegistry();
    const now = Date.now();
    for (const { cutting: c, occurredAt, daysLate } of listHayForExport({
      blockId,
      fromMs,
      toMs
    })) {
      const crop = registry.get(c.cropPluginId)?.plugin as { displayName?: string } | undefined;
      rows.push({
        id: c.id,
        occurredAtIso: new Date(occurredAt).toISOString(),
        occurredAtLocal: localStamp(occurredAt, prefs),
        blockId: c.blockId,
        blockName: blockNameById.get(c.blockId) ?? '(unknown block)',
        sprayerId: '',
        sprayerName: '',
        performedById: c.performedById ?? '',
        products: '',
        chemistryClasses: '',
        windMph: '',
        tempF: '',
        rainForecastMmNext24h: '',
        conditionsProvenance: '',
        rulesVersion: c.rulesVersion,
        pluginHashes: '',
        customRateOverride: '',
        locked: now - occurredAt >= LOCK_WINDOW_MS ? 'true' : 'false',
        record_kind: 'hay',
        crop_commodity: crop?.displayName ?? c.cropPluginId,
        moisture_pct: c.baleMoisturePct !== undefined ? String(c.baleMoisturePct) : '',
        ...lateCells(c.recordedLate, daysLate)
      });
    }
    rows.sort((a, b) => String(b.occurredAtIso).localeCompare(String(a.occurredAtIso)));
  }

  const csvBody = papa.unparse(rows, { header: true });

  // T9 — exporter signature appended as a final row. Column 1 carries the
  // metadata so spreadsheet apps render it visibly without disturbing the
  // header-on-row-1 convention. Stays out of the data rows so consumers
  // doing strict CSV ingest can simply drop the last row.
  const now = new Date();
  const generatedAt = now.toISOString();
  const signatureLine = `# Generated by CropCard v${APP_VERSION} on ${generatedAt} · exported by ${identityLabel(user)} · occurredAtLocal in ${zoneCaption(prefs, now)}`;
  const csv = `${csvBody}\n${signatureLine}\n`;
  const stamp = generatedAt.slice(0, 19).replace(/[:T]/g, '-');

  return new Response(csv, {
    headers: {
      'Content-Type': 'text/csv; charset=utf-8',
      'Content-Disposition': `attachment; filename="cropcard-spray-records-${stamp}.csv"`,
      'X-CropCard-Generator': `CropCard/${APP_VERSION}`,
      'X-CropCard-Exported-By': identityLabel(user)
    }
  });
};
