import { RULES_VERSION } from '$lib/safety/version';
import { APP_VERSION } from '$lib/version';
import { formatInstant, formatQuantity, unitLabel, zoneAbbrev, type Prefs } from '$lib/prefs';
import type { YearSummaryForViewer } from '$lib/records/yearSummary';
import { animalSectionPdf } from '$lib/records/yearSummaryAnimalsPdf';
import { CC_TABLE, PAGE, type PdfJobDoc } from '../pdfSpec';
import { signatureFooter } from './parts';

export interface YearSummaryDocInput {
  year: number;
  farmName: string;
  today: string;
  /** The viewer's `identityLabel`. */
  exporter: string;
  now: Date;
  prefs: Prefs;
  summary: YearSummaryForViewer;
  philosophyLabel: string;
}

function fmtCents(cents: number): string {
  return `$${(cents / 100).toFixed(2)}`;
}

function fmtArea(acres: number, prefs: Prefs): string {
  return formatQuantity(acres, 'area', prefs, { digits: 2, bare: true });
}

function fmtMoisture(m: { min: number | null; max: number | null; mean: number | null }): string {
  if (m.mean === null) return '—';
  return `${m.min}% / ${m.mean}% / ${m.max}%`;
}

/** `/api/records/year-summary.pdf` (UC-46). */
export function yearSummaryDoc(i: YearSummaryDocInput): PdfJobDoc {
  const { year, farmName, prefs, summary, now } = i;
  const areaHeader = `Area treated (${unitLabel('area', prefs)})`;
  const inputCosts = summary.inputCosts;
  const signatureText = `Generated by CropCard v${APP_VERSION} on ${formatInstant(now, prefs)} ${zoneAbbrev(prefs, now)} · exported by ${i.exporter}`;

  const productBody: unknown[][] = [
    [
      { text: 'Product', style: 'th' },
      { text: 'Class(es)', style: 'th' },
      { text: 'Applications', style: 'th' },
      { text: areaHeader, style: 'th' }
    ],
    ...summary.productAcreage.map((p) => [
      p.displayName,
      p.classes.join(', ') || '—',
      String(p.applicationCount),
      fmtArea(p.acresTreated, prefs)
    ])
  ];

  const classBody: unknown[][] = [
    [
      { text: 'Chemistry class', style: 'th' },
      { text: 'Applications', style: 'th' },
      { text: areaHeader, style: 'th' }
    ],
    ...summary.chemistryClassAcreage.map((c) => [
      c.className,
      String(c.applicationCount),
      fmtArea(c.acresTreated, prefs)
    ])
  ];

  const harvestBody: unknown[][] = [
    [
      { text: 'Archetype', style: 'th' },
      { text: 'Crops', style: 'th' },
      { text: 'Events', style: 'th' },
      { text: 'Moisture (min/mean/max)', style: 'th' }
    ],
    ...summary.harvestByArchetype.map((h) => [
      h.archetype,
      String(h.cropCount),
      String(h.eventCount),
      fmtMoisture(h.moisture)
    ])
  ];

  const costBody: unknown[][] | null = inputCosts
    ? [
        [
          { text: 'Category', style: 'th' },
          { text: 'Inferred spend', style: 'th' }
        ],
        ...inputCosts.lines.map((l) => [l.category, fmtCents(l.costCents)]),
        [
          { text: 'Total', bold: true },
          { text: fmtCents(inputCosts.totalCents), bold: true }
        ]
      ]
    : null;

  return {
    doc: {
      info: {
        title: `CropCard year-end summary ${year} — ${farmName}`,
        author: 'CropCard',
        subject: 'Year-end summary report (UC-46)',
        creator: `CropCard v${APP_VERSION}`,
        producer: `CropCard v${APP_VERSION}`
      },
      pageSize: 'LETTER',
      pageOrientation: 'portrait',
      pageMargins: [40, 70, 40, 50],
      content: [
        { text: `Year-end summary — ${year}`, style: 'h1' },
        {
          text: `${summary.totals.totalApplications} application(s) · ${summary.totals.harvestEvents} harvest event(s) · ${summary.totals.blocksTreated} block(s) treated · rules ${RULES_VERSION} · app v${APP_VERSION}`,
          style: 'sub',
          margin: [0, 0, 0, 12]
        },

        { text: 'Applications by product', style: 'h2' },
        summary.productAcreage.length
          ? {
              table: { headerRows: 1, widths: ['*', 'auto', 'auto', 'auto'], body: productBody },
              layout: CC_TABLE
            }
          : { text: 'No applications recorded this year.', style: 'empty' },

        { text: 'Applications by chemistry class', style: 'h2', margin: [0, 14, 0, 0] },
        summary.chemistryClassAcreage.length
          ? {
              table: { headerRows: 1, widths: ['*', 'auto', 'auto'], body: classBody },
              layout: CC_TABLE
            }
          : { text: 'No chemistry classes recorded.', style: 'empty' },

        { text: 'Philosophy compliance', style: 'h2', margin: [0, 14, 0, 0] },
        {
          text: `Evaluated against: ${i.philosophyLabel}. ${summary.philosophy.compliantApplications} compliant · ${summary.philosophy.nonCompliantApplications} non-compliant · ${summary.philosophy.unknownApplications} unclassified (of ${summary.philosophy.totalApplications} total).`,
          style: 'body'
        },

        { text: 'Harvest by archetype', style: 'h2', margin: [0, 14, 0, 0] },
        summary.harvestByArchetype.length
          ? {
              table: { headerRows: 1, widths: ['*', 'auto', 'auto', 'auto'], body: harvestBody },
              layout: CC_TABLE
            }
          : { text: 'No harvest events recorded this year.', style: 'empty' },

        ...(inputCosts && costBody
          ? [
              { text: 'Input costs', style: 'h2', margin: [0, 14, 0, 0] },
              inputCosts.lines.length
                ? {
                    table: { headerRows: 1, widths: ['*', 'auto'], body: costBody },
                    layout: CC_TABLE
                  }
                : {
                    text: 'No priced consumption recorded (lot costs may be missing).',
                    style: 'empty'
                  }
            ]
          : []),

        { text: 'Scout → spray funnel', style: 'h2', margin: [0, 14, 0, 0] },
        {
          text: `${summary.scoutFunnel.scoutObservations} scout observation(s) · ${summary.scoutFunnel.thresholdTriggeredApplications} threshold-triggered application(s) · ${summary.scoutFunnel.spraysAvoided} spray(s) avoided (observation with no follow-up application within 14 days).`,
          style: 'body'
        },

        { text: 'Decon + calibration compliance', style: 'h2', margin: [0, 14, 0, 0] },
        {
          text: `${summary.compliance.calibratedSprayerCount} of ${summary.compliance.sprayerCount} sprayer(s) calibrated · ${summary.compliance.calibratedThisYear} calibrated this year · ${summary.compliance.deconEventsThisYear} decon event(s) this year.`,
          style: 'body'
        },

        ...(summary.animals
          ? animalSectionPdf(summary.animals, year, (ms) => formatInstant(ms, prefs, 'date'))
          : []),

        {
          text: '\nDeterministic aggregate — read-only over recorded events. Retention: minimum 2 years from occurrence (NFR-05). Records are immutable after the 48-hour lock window (FR-09).',
          style: 'sub',
          margin: [0, 16, 0, 0]
        }
      ],
      styles: {
        h1: { fontSize: 18, bold: true, color: '#1f5e3a', margin: [0, 0, 0, 2] },
        h2: { fontSize: 12, bold: true, color: '#1f5e3a', margin: [0, 8, 0, 4] },
        sub: { fontSize: 9, color: '#555555' },
        body: { fontSize: 10, color: '#333333' },
        empty: { fontSize: 9, italics: true, color: '#888888' },
        th: { color: 'white', bold: true, fontSize: 9 },
        farmName: { fontSize: 13, bold: true, color: '#1f5e3a' },
        farmSub: { fontSize: 8, color: '#555555' },
        footer: { fontSize: 7, color: '#777777' }
      },
      defaultStyle: { fontSize: 10, font: 'Roboto' }
    },
    header: {
      first: {
        stack: [
          { text: `${farmName} — ${year} year in review`, style: 'farmName' },
          { text: `${i.today} · ${i.exporter}`, style: 'farmSub' }
        ],
        margin: [40, 20, 40, 0]
      },
      rest: {
        text: [`${farmName} · ${year} · page `, PAGE],
        style: 'farmSub',
        margin: [40, 20, 40, 0]
      }
    },
    footer: signatureFooter(signatureText, [40, 0, 40, 20])
  };
}
