/**
 * GET /api/records/year-summary.pdf?year=YYYY
 *
 * UC-46 — Year-end summary report as a compliance-ready PDF.
 *
 * Reuses the same server-side pdfmake pipeline as the spray-record export
 * (no headless browser). Renders the deterministic aggregate produced by
 * `buildYearSummary`: totals, acres treated by product + chemistry class,
 * philosophy roll-up, harvest totals by archetype (incl. moisture
 * min/max/mean), input costs, scout→spray funnel, and decon/calibration
 * compliance. Read-only — no writes, no migration.
 *
 * Deterministic-first (Invariant 7): this endpoint never calls Claude. The
 * tables are the product; an AI narrative would be optional enrichment.
 */

import { type RequestHandler } from '@sveltejs/kit';
import PdfPrinter from 'pdfmake';
import { eq } from 'drizzle-orm';

import { requireUser } from '$lib/server/auth';
import { db } from '$lib/db/client';
import { owners } from '$lib/db/schema';
import { unscopedQueryNote } from '$lib/db/tenant';
import { RULES_VERSION } from '$lib/safety/version';
import { APP_VERSION } from '$lib/version';
import { buildYearSummary } from '$lib/records/yearSummary.server';
import { PHILOSOPHY_LABELS } from '$lib/season/setup';

const fonts = {
  Roboto: {
    normal: 'Helvetica',
    bold: 'Helvetica-Bold',
    italics: 'Helvetica-Oblique',
    bolditalics: 'Helvetica-BoldOblique'
  }
};

const printer = new PdfPrinter(fonts);

function ownerNameOf(ownerId: string | null): string {
  if (!ownerId) return '(unknown farm)';
  unscopedQueryNote('year-summary PDF footer looks up the active Owner row for display');
  const row = db.select({ name: owners.name }).from(owners).where(eq(owners.id, ownerId)).get();
  return row?.name ?? '(unknown farm)';
}

function fmtCents(cents: number): string {
  return `$${(cents / 100).toFixed(2)}`;
}

function fmtAcres(acres: number): string {
  return acres.toFixed(2);
}

function fmtMoisture(m: { min: number | null; max: number | null; mean: number | null }): string {
  if (m.mean === null) return '—';
  return `${m.min}% / ${m.mean}% / ${m.max}%`;
}

export const GET: RequestHandler = async (event) => {
  const user = requireUser(event);
  const now = new Date();
  const yearParam = event.url.searchParams.get('year');
  const year = yearParam && /^\d{4}$/.test(yearParam) ? Number(yearParam) : now.getFullYear();

  const summary = await buildYearSummary(year, user.activeOwnerId);
  const farmName = ownerNameOf(user.activeOwnerId);

  const signatureText = `Generated by CropCard v${APP_VERSION} on ${now.toISOString()} · exported by ${user.email}`;

  // ── Table bodies ──────────────────────────────────────────────────────
  const productBody: unknown[][] = [
    [
      { text: 'Product', style: 'th' },
      { text: 'Class(es)', style: 'th' },
      { text: 'Applications', style: 'th' },
      { text: 'Acres treated', style: 'th' }
    ],
    ...summary.productAcreage.map((p) => [
      p.displayName,
      p.classes.join(', ') || '—',
      String(p.applicationCount),
      fmtAcres(p.acresTreated)
    ])
  ];

  const classBody: unknown[][] = [
    [
      { text: 'Chemistry class', style: 'th' },
      { text: 'Applications', style: 'th' },
      { text: 'Acres treated', style: 'th' }
    ],
    ...summary.chemistryClassAcreage.map((c) => [
      c.className,
      String(c.applicationCount),
      fmtAcres(c.acresTreated)
    ])
  ];

  const harvestBody: unknown[][] = [
    [
      { text: 'Archetype', style: 'th' },
      { text: 'Crops', style: 'th' },
      { text: 'Events', style: 'th' },
      { text: 'Moisture (min/mean/max)', style: 'th' }
    ],
    ...summary.harvestByArchetype.map((h) => [
      h.archetype,
      String(h.cropCount),
      String(h.eventCount),
      fmtMoisture(h.moisture)
    ])
  ];

  const costBody: unknown[][] = [
    [
      { text: 'Category', style: 'th' },
      { text: 'Inferred spend', style: 'th' }
    ],
    ...summary.inputCosts.lines.map((l) => [l.category, fmtCents(l.costCents)]),
    [
      { text: 'Total', bold: true },
      { text: fmtCents(summary.inputCosts.totalCents), bold: true }
    ]
  ];

  const philosophyLabel = PHILOSOPHY_LABELS[summary.philosophy.philosophy];

  type DocDefWithChrome = Parameters<typeof printer.createPdfKitDocument>[0] & {
    header?: (currentPage: number, pageCount: number) => unknown;
    footer?: (currentPage: number, pageCount: number) => unknown;
  };

  const docDef: DocDefWithChrome = {
    info: {
      title: `CropCard year-end summary ${year} — ${farmName}`,
      author: 'CropCard',
      subject: 'Year-end summary report (UC-46)',
      creator: `CropCard v${APP_VERSION}`,
      producer: `CropCard v${APP_VERSION}`
    },
    pageSize: 'LETTER',
    pageOrientation: 'portrait',
    pageMargins: [40, 70, 40, 50],
    header: (currentPage: number) => {
      if (currentPage === 1) {
        return {
          stack: [
            { text: `${farmName} — ${year} year in review`, style: 'farmName' },
            {
              text: `${now.toISOString().slice(0, 10)} · ${user.email}`,
              style: 'farmSub'
            }
          ],
          margin: [40, 20, 40, 0]
        };
      }
      return {
        text: `${farmName} · ${year} · page ${currentPage}`,
        style: 'farmSub',
        margin: [40, 20, 40, 0]
      };
    },
    footer: (currentPage: number, pageCount: number) => ({
      columns: [
        { text: signatureText, style: 'footer' },
        { text: `page ${currentPage} / ${pageCount}`, style: 'footer', alignment: 'right' }
      ],
      margin: [40, 0, 40, 20]
    }),
    content: [
      { text: `Year-end summary — ${year}`, style: 'h1' },
      {
        text: `${summary.totals.totalApplications} application(s) · ${summary.totals.harvestEvents} harvest event(s) · ${summary.totals.blocksTreated} block(s) treated · rules ${RULES_VERSION} · app v${APP_VERSION}`,
        style: 'sub',
        margin: [0, 0, 0, 12]
      },

      { text: 'Applications by product', style: 'h2' },
      summary.productAcreage.length
        ? {
            table: { headerRows: 1, widths: ['*', 'auto', 'auto', 'auto'], body: productBody },
            layout: tableLayout()
          }
        : { text: 'No applications recorded this year.', style: 'empty' },

      { text: 'Applications by chemistry class', style: 'h2', margin: [0, 14, 0, 0] },
      summary.chemistryClassAcreage.length
        ? {
            table: { headerRows: 1, widths: ['*', 'auto', 'auto'], body: classBody },
            layout: tableLayout()
          }
        : { text: 'No chemistry classes recorded.', style: 'empty' },

      { text: 'Philosophy compliance', style: 'h2', margin: [0, 14, 0, 0] },
      {
        text: `Evaluated against: ${philosophyLabel}. ${summary.philosophy.compliantApplications} compliant · ${summary.philosophy.nonCompliantApplications} non-compliant · ${summary.philosophy.unknownApplications} unclassified (of ${summary.philosophy.totalApplications} total).`,
        style: 'body'
      },

      { text: 'Harvest by archetype', style: 'h2', margin: [0, 14, 0, 0] },
      summary.harvestByArchetype.length
        ? {
            table: { headerRows: 1, widths: ['*', 'auto', 'auto', 'auto'], body: harvestBody },
            layout: tableLayout()
          }
        : { text: 'No harvest events recorded this year.', style: 'empty' },

      { text: 'Input costs', style: 'h2', margin: [0, 14, 0, 0] },
      summary.inputCosts.lines.length
        ? {
            table: { headerRows: 1, widths: ['*', 'auto'], body: costBody },
            layout: tableLayout()
          }
        : {
            text: 'No priced consumption recorded (lot costs may be missing).',
            style: 'empty'
          },

      { text: 'Scout → spray funnel', style: 'h2', margin: [0, 14, 0, 0] },
      {
        text: `${summary.scoutFunnel.scoutObservations} scout observation(s) · ${summary.scoutFunnel.thresholdTriggeredApplications} threshold-triggered application(s) · ${summary.scoutFunnel.spraysAvoided} spray(s) avoided (observation with no follow-up application within 14 days).`,
        style: 'body'
      },

      { text: 'Decon + calibration compliance', style: 'h2', margin: [0, 14, 0, 0] },
      {
        text: `${summary.compliance.calibratedSprayerCount} of ${summary.compliance.sprayerCount} sprayer(s) calibrated · ${summary.compliance.calibratedThisYear} calibrated this year · ${summary.compliance.deconEventsThisYear} decon event(s) this year.`,
        style: 'body'
      },

      {
        text: '\nDeterministic aggregate — read-only over recorded events. Retention: minimum 2 years from occurrence (NFR-05). Records are immutable after the 48-hour lock window (FR-09).',
        style: 'sub',
        margin: [0, 16, 0, 0]
      }
    ],
    styles: {
      h1: { fontSize: 18, bold: true, color: '#1f5e3a', margin: [0, 0, 0, 2] },
      h2: { fontSize: 12, bold: true, color: '#1f5e3a', margin: [0, 8, 0, 4] },
      sub: { fontSize: 9, color: '#555555' },
      body: { fontSize: 10, color: '#333333' },
      empty: { fontSize: 9, italics: true, color: '#888888' },
      th: { color: 'white', bold: true, fontSize: 9 },
      farmName: { fontSize: 13, bold: true, color: '#1f5e3a' },
      farmSub: { fontSize: 8, color: '#555555' },
      footer: { fontSize: 7, color: '#777777' }
    },
    defaultStyle: { fontSize: 10, font: 'Roboto' }
  };

  const pdfDoc = printer.createPdfKitDocument(docDef);
  const chunks: Buffer[] = [];
  pdfDoc.on('data', (chunk: Buffer) => chunks.push(chunk));
  pdfDoc.end();

  const buffer: Buffer = await new Promise((resolve, reject) => {
    pdfDoc.on('end', () => resolve(Buffer.concat(chunks)));
    pdfDoc.on('error', reject);
  });

  return new Response(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="cropcard-year-summary-${year}.pdf"`,
      'X-CropCard-Generator': `CropCard/${APP_VERSION}`,
      'X-CropCard-Exported-By': user.email
    }
  });
};

function tableLayout() {
  return {
    fillColor: (rowIndex: number) => (rowIndex === 0 ? '#1f5e3a' : null),
    hLineColor: () => '#cccccc',
    vLineColor: () => '#cccccc'
  };
}
