import type { MessageKey } from '$lib/i18n';

/** Built-in growth stage names (family tables and the crop plugins that
 *  author their own) to their message keys. A stage name not listed here
 *  is plugin-written text and reads as written. */
export const STAGE_NAME_KEYS: Readonly<Record<string, MessageKey>> = {
  Emergence: 'plan.cal.stage.emergence',
  '2-leaf collar': 'plan.cal.stage.n2LeafCollar',
  '4-leaf collar': 'plan.cal.stage.n4LeafCollar',
  '6-leaf collar': 'plan.cal.stage.n6LeafCollar',
  '8-leaf collar': 'plan.cal.stage.n8LeafCollar',
  Tasseling: 'plan.cal.stage.tasseling',
  Silking: 'plan.cal.stage.silking',
  Blister: 'plan.cal.stage.blister',
  Milk: 'plan.cal.stage.milk',
  Dough: 'plan.cal.stage.dough',
  Dent: 'plan.cal.stage.dent',
  'Black layer / physiological maturity': 'plan.cal.stage.blackLayerPhysiologicalMaturity',
  '2 trifoliates': 'plan.cal.stage.n2Trifoliates',
  '4 trifoliates': 'plan.cal.stage.n4Trifoliates',
  'Begin bloom': 'plan.cal.stage.beginBloom',
  'Begin pod': 'plan.cal.stage.beginPod',
  'Begin seed': 'plan.cal.stage.beginSeed',
  'Begin maturity': 'plan.cal.stage.beginMaturity',
  'Full maturity': 'plan.cal.stage.fullMaturity',
  'Coleoptile through soil': 'plan.cal.stage.coleoptileThroughSoil',
  'Tillering begins': 'plan.cal.stage.tilleringBegins',
  'Stem extension / jointing': 'plan.cal.stage.stemExtensionJointing',
  'Flag leaf fully emerged': 'plan.cal.stage.flagLeafFullyEmerged',
  Heading: 'plan.cal.stage.heading',
  'Anthesis (flowering)': 'plan.cal.stage.anthesisFlowering',
  'Milk development': 'plan.cal.stage.milkDevelopment',
  'Early dough': 'plan.cal.stage.earlyDough',
  'Fully ripe': 'plan.cal.stage.fullyRipe',
  '5-leaf': 'plan.cal.stage.n5Leaf',
  'First flower visible': 'plan.cal.stage.firstFlowerVisible',
  'Full flower': 'plan.cal.stage.fullFlower',
  'Fruit set': 'plan.cal.stage.fruitSet',
  'Fruit color change': 'plan.cal.stage.fruitColorChange',
  '5 true leaves': 'plan.cal.stage.n5TrueLeaves',
  'First flower buds': 'plan.cal.stage.firstFlowerBuds',
  'Full flowering': 'plan.cal.stage.fullFlowering',
  'Color break': 'plan.cal.stage.colorBreak',
  Cotyledon: 'plan.cal.stage.cotyledon',
  'True leaves': 'plan.cal.stage.trueLeaves',
  'Head / curd / sprout formation': 'plan.cal.stage.headCurdSproutFormation',
  'Harvest size': 'plan.cal.stage.harvestSize',
  Bolting: 'plan.cal.stage.bolting',
  'Root bulking': 'plan.cal.stage.rootBulking',
  'Over-mature': 'plan.cal.stage.overMature',
  'Fern-up': 'plan.cal.stage.fernUp',
  'Leaf development': 'plan.cal.stage.leafDevelopment',
  'Bulb initiation': 'plan.cal.stage.bulbInitiation',
  'Tops fall over': 'plan.cal.stage.topsFallOver',
  'Cure-ready': 'plan.cal.stage.cureReady',
  Establishment: 'plan.cal.stage.establishment',
  'First cut size': 'plan.cal.stage.firstCutSize',
  Regrowth: 'plan.cal.stage.regrowth',
  Flowering: 'plan.cal.stage.flowering',
  'Spring green-up': 'plan.cal.stage.springGreenUp',
  'First-cut bud / boot': 'plan.cal.stage.firstCutBudBoot',
  'Subsequent cut bud / boot': 'plan.cal.stage.subsequentCutBudBoot',
  'Canopy close': 'plan.cal.stage.canopyClose',
  'Termination window': 'plan.cal.stage.terminationWindow',
  'Seed set': 'plan.cal.stage.seedSet',
  Dormant: 'plan.cal.stage.dormant',
  'Swollen bud': 'plan.cal.stage.swollenBud',
  'Bud break': 'plan.cal.stage.budBreak',
  Bloom: 'plan.cal.stage.bloom',
  'Petal fall': 'plan.cal.stage.petalFall',
  'Fruit sizing': 'plan.cal.stage.fruitSizing',
  'Color change': 'plan.cal.stage.colorChange',
  Harvest: 'plan.cal.stage.harvest',
  Veraison: 'plan.cal.stage.veraison'
};
