/**
 * GET /api/openapi.json — public, no auth. Serves the generated OpenAPI 3.1
 * document so external agents can self-discover the surface without parsing
 * TypeScript. (Phase 24 / Sub-task C / #57.)
 *
 * The artifact at apps/web/static/openapi.json is regenerated by
 * `pnpm gen:openapi` from the registry in apps/web/scripts/gen-openapi.mjs.
 * CI runs `git diff --exit-code` on it to catch drift between intent and
 * served file.
 *
 * The document is inlined at build time (`?raw`). Reading it from a path
 * relative to this module broke in production: the bundled endpoint lives
 * under build/server/entries/**, where no static/ directory exists.
 *
 * Cached one hour (`Cache-Control: public, max-age=3600`) — agents that
 * pull the doc once per tool-build are fine; live workflows that need
 * the latest can bust via query string.
 */

import type { RequestHandler } from '@sveltejs/kit';
import openapiDoc from '../../../../static/openapi.json?raw';

export const GET: RequestHandler = async () => {
  return new Response(openapiDoc, {
    status: 200,
    headers: {
      'content-type': 'application/json',
      'cache-control': 'public, max-age=3600'
    }
  });
};
