/**
 * GET /api/openapi.json — public, no auth. Serves the generated OpenAPI 3.1
 * document so external agents can self-discover the surface without parsing
 * TypeScript. (Phase 24 / Sub-task C / #57.)
 *
 * The artifact at apps/web/static/openapi.json is regenerated by
 * `pnpm gen:openapi` from the registry in apps/web/scripts/gen-openapi.mjs.
 * CI runs `git diff --exit-code` on it to catch drift between intent and
 * served file.
 *
 * Cached one hour (`Cache-Control: public, max-age=3600`) — agents that
 * pull the doc once per tool-build are fine; live workflows that need
 * the latest can bust via query string.
 */

import type { RequestHandler } from '@sveltejs/kit';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
// Layout: apps/web/src/routes/api/openapi.json/+server.ts → ../../../../static/openapi.json
const ARTIFACT_PATH = resolve(__dirname, '../../../../static/openapi.json');

let cachedJson: string | null = null;

async function loadJson(): Promise<string> {
  if (cachedJson !== null) return cachedJson;
  cachedJson = await readFile(ARTIFACT_PATH, 'utf-8');
  return cachedJson;
}

export const GET: RequestHandler = async () => {
  const json = await loadJson();
  return new Response(json, {
    status: 200,
    headers: {
      'content-type': 'application/json',
      'cache-control': 'public, max-age=3600'
    }
  });
};
