/**
 * GET /api/spray/records/export.pdf
 *
 * Streams a compliance-ready PDF of all spray records (FR-09, NFR-05).
 * Uses pdfmake server-side; no headless browser dependency.
 *
 * B-04 (Sprint D' close) additions:
 *   T1 — block name shown alongside the block ID in the table row.
 *   T2 — sprayer name shown alongside the sprayer ID in the table row.
 *   T5 — farm context header on page 1 (farm name + export date + owner
 *        email + filter context). Lets an inspector identify the farm
 *        without cross-referencing another document.
 *   T9 — exporter signature footer on every page ("Generated by CropCard
 *        v{X} on {date} · exported by {email}").
 *
 * The integrity hash on the cover page is a SHA-256 of the canonical record
 * payload — pair with NFR-10 ("Record exports include a digital hash for
 * integrity verification").
 */

import { createHash } from 'node:crypto';
import { type RequestHandler } from '@sveltejs/kit';
import PdfPrinter from 'pdfmake';
import { eq } from 'drizzle-orm';

import { evaluateLock, listSprayEvents } from '$lib/db/sprayEvents';
import { listBlocks } from '$lib/db/blocks';
import { listSprayers } from '$lib/db/sprayers';
import { RULES_VERSION } from '$lib/safety/version';
import { requireUser } from '$lib/server/auth';
import { db } from '$lib/db/client';
import { owners } from '$lib/db/schema';
import { unscopedQueryNote } from '$lib/db/tenant';
import { APP_VERSION } from '$lib/version';

const fonts = {
  Roboto: {
    normal: 'Helvetica',
    bold: 'Helvetica-Bold',
    italics: 'Helvetica-Oblique',
    bolditalics: 'Helvetica-BoldOblique'
  }
};

const printer = new PdfPrinter(fonts);

function ownerNameOf(ownerId: string | null): string {
  if (!ownerId) return '(unknown farm)';
  unscopedQueryNote('export footer looks up the active Owner row for display');
  const row = db.select({ name: owners.name }).from(owners).where(eq(owners.id, ownerId)).get();
  return row?.name ?? '(unknown farm)';
}

export const GET: RequestHandler = async (event) => {
  const user = requireUser(event);
  const sprayerId = event.url.searchParams.get('sprayerId') ?? undefined;
  const blockId = event.url.searchParams.get('blockId') ?? undefined;
  const events = listSprayEvents({ limit: 10_000, sprayerId, blockId });
  const generatedAt = new Date();

  const blockNameById = new Map(listBlocks().map((b) => [b.id, b.blockLabel ?? b.name]));
  const sprayerNameById = new Map(listSprayers().map((s) => [s.id, s.label]));
  const farmName = ownerNameOf(user.activeOwnerId);

  const payload = events.map((e) => ({
    id: e.id,
    occurredAt: e.occurredAt,
    blockId: e.blockId,
    sprayerId: e.sprayerId,
    products: e.products.map((p) => p.pluginId).sort(),
    rulesVersion: e.rulesVersion,
    pluginHashes: e.pluginHashes
  }));
  const integrityHash = createHash('sha256').update(JSON.stringify(payload)).digest('hex');

  // T5 — filter-context line so the export's scope is unambiguous.
  const filterContext: string[] = [];
  if (sprayerId) {
    filterContext.push(`sprayer: ${sprayerNameById.get(sprayerId) ?? sprayerId}`);
  }
  if (blockId) {
    filterContext.push(`block: ${blockNameById.get(blockId) ?? blockId}`);
  }
  const filterLine =
    filterContext.length > 0
      ? `Filtered to ${filterContext.join(' · ')}.`
      : 'No filters applied — full record set.';

  const tableBody: unknown[][] = [
    [
      { text: 'When', style: 'th' },
      { text: 'Block', style: 'th' },
      { text: 'Sprayer', style: 'th' },
      { text: 'Products', style: 'th' },
      { text: 'Conditions', style: 'th' },
      { text: 'Rules', style: 'th' },
      { text: 'State', style: 'th' }
    ]
  ];

  for (const e of events) {
    const locked = evaluateLock(e) !== undefined;
    const blockLabel = blockNameById.get(e.blockId);
    const sprayerLabel = sprayerNameById.get(e.sprayerId);
    tableBody.push([
      new Date(e.occurredAt).toISOString().replace('T', ' ').slice(0, 16),
      // T1 — name first (human-readable), id as secondary line.
      [
        { text: blockLabel ?? '(unknown block)' },
        { text: e.blockId.slice(0, 8) + '…', style: 'mono' }
      ],
      // T2 — same treatment for sprayer.
      [
        { text: sprayerLabel ?? '(unknown sprayer)' },
        { text: e.sprayerId.slice(0, 8) + '…', style: 'mono' }
      ],
      e.products.map((p) => p.pluginId).join('\n'),
      `${e.conditions.windMph} mph\n${e.conditions.tempF}°F\n${e.conditions.rainForecastMmNext24h} mm`,
      { text: e.rulesVersion, style: 'mono' },
      [locked ? '🔒 locked' : 'editable', e.customRateOverride ? '\n⚠ custom rate' : ''].join('')
    ]);
  }

  // T9 — exporter signature, rendered on every page footer.
  const signatureText = `Generated by CropCard v${APP_VERSION} on ${generatedAt.toISOString()} · exported by ${user.email}`;

  // pdfmake's type definitions for DocumentDefinition omit the runtime-
  // supported `header` / `footer` callbacks (https://pdfmake.github.io/docs/0.1/document-definition-object/page/).
  // Cast through a permissive shape so the typed surface stays narrow
  // while letting us use the actually-supported runtime features.
  type DocDefWithChrome = Parameters<typeof printer.createPdfKitDocument>[0] & {
    header?: (currentPage: number, pageCount: number) => unknown;
    footer?: (currentPage: number, pageCount: number) => unknown;
  };

  const docDef: DocDefWithChrome = {
    info: {
      title: `CropCard spray records — ${farmName}`,
      author: 'CropCard',
      subject: 'Spray-record compliance export',
      creator: `CropCard v${APP_VERSION}`,
      producer: `CropCard v${APP_VERSION}`
    },
    pageSize: 'LETTER',
    pageOrientation: 'landscape',
    pageMargins: [40, 80, 40, 60],
    // T5 — farm context header on every page (page 1 gets the full block;
    // subsequent pages get a slimmer "farm — date — page N" header).
    header: (currentPage: number) => {
      if (currentPage === 1) {
        return {
          stack: [
            { text: farmName, style: 'farmName' },
            {
              text: `${generatedAt.toISOString().slice(0, 10)} · ${user.email} · ${filterLine}`,
              style: 'farmSub'
            }
          ],
          margin: [40, 24, 40, 0]
        };
      }
      return {
        text: `${farmName} · ${generatedAt.toISOString().slice(0, 10)} · page ${currentPage}`,
        style: 'farmSub',
        margin: [40, 24, 40, 0]
      };
    },
    // T9 — exporter signature on every page.
    footer: (currentPage: number, pageCount: number) => ({
      columns: [
        { text: signatureText, style: 'footer' },
        { text: `page ${currentPage} / ${pageCount}`, style: 'footer', alignment: 'right' }
      ],
      margin: [40, 0, 40, 24]
    }),
    content: [
      { text: 'CropCard — Spray-record export', style: 'h1' },
      {
        text: `${events.length} record(s) · rules ${RULES_VERSION} · app v${APP_VERSION}`,
        style: 'sub'
      },
      {
        text: `Integrity hash: ${integrityHash}`,
        style: 'mono',
        margin: [0, 0, 0, 12]
      },
      {
        table: {
          headerRows: 1,
          widths: ['auto', 80, 80, '*', '*', 'auto', 'auto'],
          body: tableBody
        },
        layout: {
          fillColor: (rowIndex: number) => (rowIndex === 0 ? '#1f5e3a' : null),
          hLineColor: () => '#cccccc',
          vLineColor: () => '#cccccc'
        }
      },
      {
        text: '\nRetention: minimum 2 years from occurrence (NFR-05). Records are immutable after the 48-hour lock window (FR-09). Plugin hashes embedded per record allow tamper-evident auditing.',
        style: 'sub',
        margin: [0, 16, 0, 0]
      }
    ],
    styles: {
      h1: { fontSize: 16, bold: true, color: '#1f5e3a', margin: [0, 0, 0, 4] },
      sub: { fontSize: 9, color: '#555555' },
      th: { color: 'white', bold: true, fontSize: 9 },
      mono: { fontSize: 8, color: '#1f5e3a' },
      farmName: { fontSize: 13, bold: true, color: '#1f5e3a' },
      farmSub: { fontSize: 8, color: '#555555' },
      footer: { fontSize: 8, color: '#777777' }
    },
    defaultStyle: { fontSize: 9, font: 'Roboto' }
  };

  const pdfDoc = printer.createPdfKitDocument(docDef);
  const chunks: Buffer[] = [];
  pdfDoc.on('data', (chunk: Buffer) => chunks.push(chunk));
  pdfDoc.end();

  const buffer: Buffer = await new Promise((resolve, reject) => {
    pdfDoc.on('end', () => resolve(Buffer.concat(chunks)));
    pdfDoc.on('error', reject);
  });

  const stamp = generatedAt.toISOString().slice(0, 19).replace(/[:T]/g, '-');

  return new Response(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="cropcard-spray-records-${stamp}.pdf"`,
      'X-CropCard-Generator': `CropCard/${APP_VERSION}`,
      'X-CropCard-Exported-By': user.email
    }
  });
};
