/**
 * GET /api/spray/records/export.pdf
 *
 * Streams a compliance-ready PDF of all spray records (FR-09, NFR-05).
 * Uses pdfmake server-side; no headless browser dependency.
 *
 * B-04 (Sprint D' close) additions:
 *   T1 — block name shown alongside the block ID in the table row.
 *   T2 — sprayer name shown alongside the sprayer ID in the table row.
 *   T5 — farm context header on page 1 (farm name + export date + owner
 *        email + filter context). Lets an inspector identify the farm
 *        without cross-referencing another document.
 *   T9 — exporter signature footer on every page ("Generated by CropCard
 *        v{X} on {date} · exported by {email}").
 *
 * #761: insecticide and fungicide applications are listed too, each row
 * names its kind, and products show their names. The hash payload of a
 * herbicide row is unchanged; insecticide and fungicide rows add their own
 * entries (with `kind`), so a range holding them hashes differently.
 *
 * The integrity hash on the cover page is a SHA-256 of the canonical record
 * payload — pair with NFR-10 ("Record exports include a digital hash for
 * integrity verification").
 */

import { createHash } from 'node:crypto';
import { type RequestEvent, type RequestHandler } from '@sveltejs/kit';
import { renderPdf } from '$lib/server/pdf';
import { sprayExportDoc } from '$lib/server/render/docs/spray';
import { withRenderRefusal } from '$lib/server/render/refusal';
import { eq } from 'drizzle-orm';

import { evaluateLock, listSprayEvents } from '$lib/db/sprayEvents';
import { listInsecticideEvents } from '$lib/db/insecticideEvents';
import { listFungicideEvents } from '$lib/db/fungicideEvents';
import { getRegistry } from '$lib/server/registry';
import { lockedNow } from '$lib/records/exportFacts';
import { listBlocks } from '$lib/db/blocks';
import { listSprayers } from '$lib/db/sprayers';
import { requireUser } from '$lib/server/auth';
import { parseExportDateRange } from '$lib/exports/dateRange';
import { localDay, localStamp, zoneCaption } from '$lib/exports/localTime';
import { prefsFor } from '$lib/db/userProfile';
import { formatInstant, zoneAbbrev } from '$lib/prefs';
import { db } from '$lib/db/client';
import { owners } from '$lib/db/schema';
import { unscopedQueryNote } from '$lib/db/tenant';
import { APP_VERSION } from '$lib/version';
import { identityLabel } from '$lib/identity';

function ownerNameOf(ownerId: string | null): string {
  if (!ownerId) return '(unknown farm)';
  unscopedQueryNote('export footer looks up the active Owner row for display');
  const row = db.select({ name: owners.name }).from(owners).where(eq(owners.id, ownerId)).get();
  return row?.name ?? '(unknown farm)';
}

export const GET: RequestHandler = (event) => withRenderRefusal(event, () => exportPdf(event));

async function exportPdf(event: RequestEvent): Promise<Response> {
  const user = requireUser(event);
  const prefs = prefsFor(user.id);
  const sprayerId = event.url.searchParams.get('sprayerId') ?? undefined;
  const blockId = event.url.searchParams.get('blockId') ?? undefined;
  const { fromMs, toMs } = parseExportDateRange(event.url.searchParams, prefs);
  const events = listSprayEvents({ sprayerId, blockId, fromMs, toMs });
  const onSprayer = (e: { sprayerId?: string | null }) => !sprayerId || e.sprayerId === sprayerId;
  const insecticides = listInsecticideEvents({ blockId, fromMs, toMs }).filter(onSprayer);
  const fungicides = listFungicideEvents({ blockId, fromMs, toMs }).filter(onSprayer);
  const registry = await getRegistry();
  const productName = (pluginId: string) => {
    const plugin = registry.get(pluginId)?.plugin;
    return plugin && 'displayName' in plugin ? plugin.displayName : pluginId;
  };
  const generatedAt = new Date();
  const generatedDay = localDay(generatedAt, prefs);

  const blockNameById = new Map(listBlocks().map((b) => [b.id, b.blockLabel ?? b.name]));
  const sprayerNameById = new Map(listSprayers().map((s) => [s.id, s.label]));
  const farmName = ownerNameOf(user.activeOwnerId);

  const payload: Record<string, unknown>[] = events.map((e) => ({
    id: e.id,
    occurredAt: e.occurredAt,
    blockId: e.blockId,
    sprayerId: e.sprayerId,
    products: e.products.map((p) => p.pluginId).sort(),
    rulesVersion: e.rulesVersion,
    pluginHashes: e.pluginHashes
  }));
  for (const [kind, list] of [
    ['insecticide', insecticides],
    ['fungicide', fungicides]
  ] as const) {
    for (const e of list) {
      payload.push({
        kind,
        id: e.id,
        occurredAt: e.occurredAt,
        blockId: e.blockId,
        sprayerId: e.sprayerId ?? '',
        products: e.products.map((p) => p.pluginId).sort(),
        rulesVersion: e.rulesVersion,
        pluginHashes: e.pluginHashes
      });
    }
  }
  const integrityHash = createHash('sha256').update(JSON.stringify(payload)).digest('hex');

  // T5 — filter-context line so the export's scope is unambiguous.
  const filterContext: string[] = [];
  if (sprayerId) {
    filterContext.push(`sprayer: ${sprayerNameById.get(sprayerId) ?? sprayerId}`);
  }
  if (blockId) {
    filterContext.push(`block: ${blockNameById.get(blockId) ?? blockId}`);
  }
  const filterLine =
    filterContext.length > 0
      ? `Filtered to ${filterContext.join(' · ')}.`
      : 'No filters applied — full record set.';

  const tableBody: unknown[][] = [
    [
      { text: `When (${zoneCaption(prefs, generatedAt)})`, style: 'th' },
      { text: 'Block', style: 'th' },
      { text: 'Sprayer', style: 'th' },
      { text: 'Products', style: 'th' },
      { text: 'Conditions', style: 'th' },
      { text: 'Rules', style: 'th' },
      { text: 'State', style: 'th' }
    ]
  ];

  interface Row {
    kind: 'herbicide' | 'insecticide' | 'fungicide';
    occurredAt: number;
    blockId: string;
    sprayerId?: string;
    products: string[];
    conditions: string;
    rulesVersion: string;
    locked: boolean;
    customRate: boolean;
  }
  const rows: Row[] = [
    ...events.map((e) => ({
      kind: 'herbicide' as const,
      occurredAt: e.occurredAt,
      blockId: e.blockId,
      sprayerId: e.sprayerId,
      products: e.products.map((p) => productName(p.pluginId)),
      conditions: `${e.conditions.windMph} mph\n${e.conditions.tempF}°F\n${e.conditions.rainForecastMmNext24h} mm`,
      rulesVersion: e.rulesVersion,
      locked: evaluateLock(e) !== undefined,
      customRate: e.customRateOverride === true
    })),
    ...insecticides.map((e) => ({
      kind: 'insecticide' as const,
      occurredAt: e.occurredAt,
      blockId: e.blockId,
      sprayerId: e.sprayerId,
      products: e.products.map((p) => p.displayName || productName(p.pluginId)),
      conditions: `${e.conditions.windMph} mph\n${e.conditions.tempF}°F`,
      rulesVersion: e.rulesVersion,
      locked: lockedNow(e),
      customRate: false
    })),
    ...fungicides.map((e) => ({
      kind: 'fungicide' as const,
      occurredAt: e.occurredAt,
      blockId: e.blockId,
      sprayerId: e.sprayerId,
      products: e.products.map((p) => p.displayName || productName(p.pluginId)),
      conditions: `${e.conditions.windMph} mph\n${e.conditions.tempF}°F`,
      rulesVersion: e.rulesVersion,
      locked: lockedNow(e),
      customRate: false
    }))
  ].sort((a, b) => b.occurredAt - a.occurredAt);

  for (const r of rows) {
    const blockLabel = blockNameById.get(r.blockId);
    const sprayerLabel = r.sprayerId ? sprayerNameById.get(r.sprayerId) : undefined;
    tableBody.push([
      localStamp(r.occurredAt, prefs),
      // T1 — name first (human-readable), id as secondary line.
      [
        { text: blockLabel ?? '(unknown block)' },
        { text: r.blockId.slice(0, 8) + '…', style: 'mono' }
      ],
      // T2 — same treatment for sprayer.
      r.sprayerId
        ? [
            { text: sprayerLabel ?? '(unknown sprayer)' },
            { text: r.sprayerId.slice(0, 8) + '…', style: 'mono' }
          ]
        : 'Not recorded',
      [{ text: r.kind, bold: true }, { text: r.products.join('\n') }],
      r.conditions,
      { text: r.rulesVersion, style: 'mono' },
      [r.locked ? 'locked' : 'editable', r.customRate ? '\ncustom rate' : ''].join('')
    ]);
  }

  // T9 — exporter signature, rendered on every page footer.
  const signatureText = `Generated by CropCard v${APP_VERSION} on ${formatInstant(generatedAt, prefs)} ${zoneAbbrev(prefs, generatedAt)} · exported by ${identityLabel(user)}`;

  const spec = sprayExportDoc({
    farmName,
    generatedDay,
    exporter: identityLabel(user),
    filterLine,
    signatureText,
    recordCount: rows.length,
    integrityHash,
    tableBody
  });

  const buffer = await renderPdf(spec, {
    ownerId: user.activeOwnerId ?? '',
    signal: event.request?.signal
  });

  const stamp = generatedAt.toISOString().slice(0, 19).replace(/[:T]/g, '-');

  return new Response(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="cropcard-spray-records-${stamp}.pdf"`,
      'X-CropCard-Generator': `CropCard/${APP_VERSION}`,
      'X-CropCard-Exported-By': identityLabel(user)
    }
  });
}
