// @vitest-environment node
/**
 * R-03: the `PdfJobDoc` builders render the same bytes as today's
 * function-based builders (frozen in `__reference__/exportDocsV0.ts`) from
 * the same data, with the creation date pinned. pdfkit is deterministic
 * once `info.creationDate` is fixed, so the bytes are compared directly.
 */
import { describe, expect, it } from 'vitest';
import { identityLabel } from '$lib/identity';
import { formatInstant, zoneAbbrev } from '$lib/prefs';
import { APP_VERSION } from '$lib/version';
import { executeRenderJob } from './jobs';
import type { PdfJobDoc } from './pdfSpec';
import { sprayExportDoc } from './docs/spray';
import { vdacsDoc } from './docs/vdacs';
import { yearSummaryDoc } from './docs/yearSummary';
import { treatmentLogDoc } from './docs/treatmentLog';
import { organicPackSummaryDoc } from './docs/organicPackSummary';
import {
  organicPackSummaryDocV0,
  renderReference,
  sprayExportDocV0,
  treatmentLogDocV0,
  vdacsDocV0,
  yearSummaryDocV0,
  type PdfDocDefinition
} from './__reference__/exportDocsV0';
import {
  exportTable,
  NOW,
  packData,
  PREFS,
  treatmentRows,
  VIEWER,
  yearSummary
} from './__reference__/fixtures';

const PINNED = new Date('2026-01-02T03:04:05Z');

async function renderNew(spec: PdfJobDoc): Promise<Buffer> {
  spec.doc.info = { ...spec.doc.info, creationDate: PINNED };
  const r = await executeRenderJob({ kind: 'pdf', spec: structuredClone(spec) });
  if (r.kind !== 'pdf') throw new Error('expected pdf');
  return Buffer.from(r.bytes);
}

function renderOld(def: PdfDocDefinition): Promise<Buffer> {
  def.info = { ...def.info, creationDate: PINNED };
  return renderReference(def);
}

function pageCount(pdf: Buffer): number {
  return (pdf.toString('latin1').match(/\/Type \/Page\b/g) ?? []).length;
}

const signatureText = `Generated by CropCard v${APP_VERSION} on ${formatInstant(NOW, PREFS)} ${zoneAbbrev(PREFS, NOW)} · exported by ${identityLabel(VIEWER)}`;

describe('render equivalence with the pre-36 builders (R-03)', () => {
  it('spray export', async () => {
    const tableBody = exportTable(160, 7);
    const common = {
      farmName: 'Hill {$cc:page} Farm',
      generatedDay: 'Sep 30, 2026',
      filterLine: 'No filters applied — full record set.',
      signatureText,
      integrityHash: 'a'.repeat(64)
    };
    const old = await renderOld(
      sprayExportDocV0({
        ...common,
        user: VIEWER,
        events: { length: 160 },
        tableBody: structuredClone(tableBody)
      })
    );
    const next = await renderNew(
      sprayExportDoc({
        ...common,
        exporter: identityLabel(VIEWER),
        recordCount: 160,
        tableBody: structuredClone(tableBody)
      })
    );
    expect(pageCount(next)).toBeGreaterThan(2);
    expect(next.equals(old)).toBe(true);
  });

  it('VDACS audit pack', async () => {
    const tableBody = exportTable(140, 12);
    const common = {
      farmName: 'Hill Farm',
      generatedDay: 'Sep 30, 2026',
      filterLine: 'Filtered to from: 2026-01-01.',
      signatureText,
      integrityHash: 'b'.repeat(64)
    };
    const old = await renderOld(
      vdacsDocV0({
        ...common,
        user: VIEWER,
        unified: { length: 140 },
        tableBody: structuredClone(tableBody)
      })
    );
    const next = await renderNew(
      vdacsDoc({
        ...common,
        exporter: identityLabel(VIEWER),
        recordCount: 140,
        tableBody: structuredClone(tableBody)
      })
    );
    expect(pageCount(next)).toBeGreaterThan(2);
    expect(next.equals(old)).toBe(true);
  });

  it.each([true, false])('year summary (costs shown: %s)', async (withCosts) => {
    const input = {
      year: 2026,
      farmName: 'Hill Farm',
      today: '2026-09-30',
      now: NOW,
      prefs: PREFS,
      summary: yearSummary(withCosts),
      philosophyLabel: 'Conventional'
    };
    const old = await renderOld(yearSummaryDocV0({ ...input, user: VIEWER }));
    const next = await renderNew(yearSummaryDoc({ ...input, exporter: identityLabel(VIEWER) }));
    expect(pageCount(next)).toBeGreaterThan(1);
    expect(next.equals(old)).toBe(true);
  });

  it.each(['log', 'pack'] as const)('animal treatment log (%s footer)', async (footer) => {
    const rows = treatmentRows(90);
    const opts = { farmName: 'Hill Farm', from: '2026-01-01', to: '2026-12-31', footer };
    const old = await renderOld(
      treatmentLogDocV0(rows, { ...opts, viewer: VIEWER, prefs: PREFS, now: NOW })
    );
    const next = await renderNew(
      treatmentLogDoc(rows, { ...opts, exporter: identityLabel(VIEWER), prefs: PREFS, now: NOW })
    );
    expect(pageCount(next)).toBeGreaterThan(2);
    expect(next.equals(old)).toBe(true);
  });

  it('animal treatment log with no rows', async () => {
    const opts = {
      farmName: 'Hill Farm',
      from: '2026-01-01',
      to: '2026-01-31',
      footer: 'log' as const
    };
    const old = await renderOld(
      treatmentLogDocV0([], { ...opts, viewer: VIEWER, prefs: PREFS, now: NOW })
    );
    const next = await renderNew(
      treatmentLogDoc([], { ...opts, exporter: identityLabel(VIEWER), prefs: PREFS, now: NOW })
    );
    expect(next.equals(old)).toBe(true);
  });

  it.each([true, false])('certifier pack summary (documents: %s)', async (withDocuments) => {
    const data = packData();
    const old = await renderOld(
      organicPackSummaryDocV0(data, { viewer: VIEWER, prefs: PREFS, now: NOW, withDocuments })
    );
    const next = await renderNew(
      organicPackSummaryDoc(data, {
        exporter: identityLabel(VIEWER),
        prefs: PREFS,
        now: NOW,
        withDocuments
      })
    );
    expect(pageCount(next)).toBeGreaterThan(1);
    expect(next.equals(old)).toBe(true);
  });
});
