// CropCard — Azure Container Apps deployment.
//
// Cheap, single-replica, scale-to-zero. Single-writer SQLite + Litestream → Blob.
// Everything lives in its own resource group; nothing is shared with other apps
// in the subscription.
//
// The container registry is created by scripts/deploy-azure.sh before this runs
// (the app needs an image to pull at creation time). This template grants the
// app's identity AcrPull on it.

@description('Project tag, also used as a name prefix.')
param project string = 'cropcard'

@description('Environment short name (dev | prod).')
param env string = 'dev'

@description('Azure region.')
param location string = resourceGroup().location

@description('Container image reference for the web app, e.g. cropcardacr.azurecr.io/cropcard-web:abc1234.')
param image string

@description('Login server of an ACR in this resource group, e.g. cropcardacr.azurecr.io. Empty = public image, no registry auth.')
param containerRegistryServer string = ''

@description('Name of the Key Vault (created by scripts/deploy-azure.sh) holding the app secrets.')
param keyVaultName string

@description('UC-17 sign-in mode. magic-link disables the direct/demo sign-in.')
@allowed(['magic-link', 'direct'])
param authMode string = 'magic-link'

@description('Key Vault holds a postmark-token secret. False = magic links and invites are written to the container log instead of emailed.')
param hasPostmarkToken bool = false

@description('Key Vault holds a pingram-api-key secret. Sends email (over Postmark when both are present) and the SMS sign-in codes; without it codes are written to the container log.')
param hasPingramKey bool = false

@description('From-address for outbound email (Postmark sender signature, or a Pingram verified domain; empty uses Pingram\'s built-in sender).')
param emailFrom string = ''

@description('Key Vault holds an anthropic-api-key secret. False = no-key mode (Invariant 7: deterministic fallbacks).')
param hasAnthropicKey bool = false

@description('Optional pass-through secrets present in the Key Vault (listed by deploy-azure.sh). Each one listed in passThroughEnv becomes a secret-backed env var; absent ones leave that feature in its honest "not configured" state.')
param presentSecrets array = []

@description('Deployment-wide AI brake: total Anthropic spend across all farms per UTC month, in USD. Empty = no brake.')
param aiGlobalMonthlyUsdCap string = ''

@description('Total AI spend across all free-plan farms per UTC month, in USD. Past it, free AI falls back to deterministic results. Empty = the app default.')
param aiFreePoolMonthlyUsd string = ''

@description('DNS zone hosted for the custom hostnames, e.g. cropcard.io. Empty = default ACA hostname only.')
param dnsZoneName string = ''

@description('Labels of dnsZoneName bound to the web app, \'@\' for the apex, e.g. [\'app\', \'www\', \'@\']. The first becomes ORIGIN; the rest redirect to it.')
param customHosts array = []

@description('Extra TXT records in dnsZoneName, relative name → value (mail DKIM and the like). Each value must fit one 255-char string.')
param dnsTxtRecords object = {}

type mxRecord = {
  preference: int
  exchange: string
}

@description('MX records in dnsZoneName, relative name → exchanges, e.g. the Pingram/SES custom MAIL FROM subdomain.')
param dnsMxRecords { *: mxRecord[] } = {}

@description('Public DNS for every custom hostname already resolves to this app (checked by deploy-azure.sh). Gates the hostname bindings and the managed certificate requests.')
param customDomainDnsReady bool = false

@description('Every custom hostname\'s managed certificate has been issued (checked by deploy-azure.sh). Gates the TLS bindings and switching ORIGIN to the custom domain.')
param customDomainCertIssued bool = false

@description('Key Vault holds a push-tick-secret (generated by deploy-azure.sh). Enables the twice-daily push-tick job and the app endpoint it calls.')
param hasPushTickSecret bool = false

@description('Key Vault holds vapid-public-key + vapid-private-key (./scripts/set-azure-secret.sh vapid --generate). False = Web Push off; push ticks report vapid-not-configured.')
param hasVapidKeys bool = false

@description('VAPID subject (mailto: or https:) sent to push services with each Web Push request. Used only when hasVapidKeys.')
param vapidSubject string = 'mailto:hello@cropcard.io'

@description('Deploy the plugin marketplace app (with its ClamAV sidecar). The web app does not depend on it.')
param deployMarketplace bool = false

@description('Container image reference for the marketplace.')
param marketplaceImage string = image

@description('Comma-separated list of operator emails allowed to sign in to the marketplace admin UI.')
param marketplaceAdminEmails string = ''

@description('Key Vault holds a marketplace-seed-credential secret (format ccm_<base64url>).')
param hasMarketplaceSeed bool = false

@description('Address that receives operational alerts (5xx, restarts, replication errors, handoff timeouts). Empty = alerts fire with no receiver.')
param alertEmail string = ''

// Names
var prefix = '${project}-${env}'
var storageName = toLower(replace('${prefix}stg', '-', ''))
var logsName = '${prefix}-logs'
var envName = '${prefix}-cae'
var appName = '${prefix}-app'
var identityName = '${prefix}-id'
var marketplaceAppName = '${prefix}-marketplace'
var blobContainerName = 'cropcard'
var marketplaceBlobContainerName = 'cropcard-marketplace'
var useRegistry = !empty(containerRegistryServer)
var acrName = useRegistry ? split(containerRegistryServer, '.')[0] : 'none'
var kvSecretsUserRoleId = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4633458b-17de-408a-b874-0445c86b69e6')
var useDomain = !empty(dnsZoneName) && !empty(customHosts)
var bindDomain = useDomain && customDomainDnsReady
var domainTls = bindDomain && customDomainCertIssued
var customFqdns = [for h in customHosts: h == '@' ? dnsZoneName : '${h}.${dnsZoneName}']
var subdomainHosts = filter(customHosts, h => h != '@')
var hasApex = contains(customHosts, '@')
var acrPullRoleId = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '7f951dda-4ed3-4680-a7ca-43fe172d538d')

// ─── Storage account + blob container for Litestream replicas ──────────
// The replica is the only durable copy of the database (the container disk is
// ephemeral), so the account is protected like a backup:
//   - GRS: a second, asynchronous copy in the paired region. GZRS would add
//     zone redundancy in the primary region, but moving an existing LRS
//     account to a zonal SKU is a conversion request, not a property change
//     this template can make; GRS is an in-place update and covers the loss
//     of the whole primary region, which LRS does not.
//   - Hot: scale-to-zero means a restore (many reads) on every cold start and
//     a snapshot every hour; Cool bills those reads and early deletes.
//   - Versioning + 14-day blob and container soft delete: a deleted or
//     overwritten snapshot/WAL segment stays recoverable
//     (docs/ops/restore-runbook.md). Old versions expire via the lifecycle
//     policy below.
resource storage 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: storageName
  location: location
  sku: { name: 'Standard_GRS' }
  kind: 'StorageV2'
  properties: {
    accessTier: 'Hot'
    minimumTlsVersion: 'TLS1_2'
    allowBlobPublicAccess: false
    supportsHttpsTrafficOnly: true
  }
}

resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2023-05-01' = {
  parent: storage
  name: 'default'
  properties: {
    isVersioningEnabled: true
    deleteRetentionPolicy: { enabled: true, days: 14 }
    containerDeleteRetentionPolicy: { enabled: true, days: 14 }
  }
}

// Previous versions are kept 30 days (longer than Litestream's 7-day
// retention and the 14-day soft delete), except the handoff lease records,
// which are rewritten every 20 s while the app runs.
resource blobLifecycle 'Microsoft.Storage/storageAccounts/managementPolicies@2023-05-01' = {
  parent: storage
  name: 'default'
  properties: {
    policy: {
      rules: [
        {
          name: 'expire-old-versions'
          enabled: true
          type: 'Lifecycle'
          definition: {
            filters: { blobTypes: ['blockBlob'] }
            actions: { version: { delete: { daysAfterCreationGreaterThan: 30 } } }
          }
        }
        {
          name: 'expire-handoff-lease-versions'
          enabled: true
          type: 'Lifecycle'
          definition: {
            filters: { blobTypes: ['blockBlob'], prefixMatch: ['${blobContainerName}/_ops/handoff/'] }
            actions: { version: { delete: { daysAfterCreationGreaterThan: 1 } } }
          }
        }
      ]
    }
  }
}

resource blobContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  parent: blobService
  name: blobContainerName
}

// Separate blob container so the two apps' WAL frames can't collide.
resource marketplaceBlobContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = if (deployMarketplace) {
  parent: blobService
  name: marketplaceBlobContainerName
}

// ─── Log Analytics workspace (required by ACA) ─────────────────────────
resource logs 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: logsName
  location: location
  properties: {
    sku: { name: 'PerGB2018' }
    retentionInDays: 30
  }
}

// ─── Registry pull identity ────────────────────────────────────────────
// User-assigned so the AcrPull grant exists before the Container App is
// created; a system-assigned identity can't be granted until the app exists,
// and the app can't be created until it can pull.
resource identity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: identityName
  location: location
}

resource acr 'Microsoft.ContainerRegistry/registries@2023-07-01' existing = if (useRegistry) {
  name: acrName
}

resource acrPull 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (useRegistry) {
  name: guid(resourceGroup().id, identity.id, acrPullRoleId)
  scope: acr
  properties: {
    principalId: identity.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: acrPullRoleId
  }
}

// ─── Key Vault secrets ─────────────────────────────────────────────────
// The vault is created (and auth-secret seeded) by the deploy script so the
// session secret never passes through a template parameter. The storage key
// is written here so it never leaves ARM.
resource kv 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
  name: keyVaultName
}

resource storageKeySecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: kv
  name: 'storage-key'
  properties: {
    value: storage.listKeys().keys[0].value
    contentType: 'Litestream replica account key (managed by main.bicep)'
  }
}

resource kvSecretsUser 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(kv.id, identity.id, kvSecretsUserRoleId)
  scope: kv
  properties: {
    principalId: identity.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: kvSecretsUserRoleId
  }
}

resource kvAudit 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'audit-to-log-analytics'
  scope: kv
  properties: {
    workspaceId: logs.id
    logs: [{ categoryGroup: 'audit', enabled: true }]
  }
}

// Container App secrets that resolve from Key Vault via the app identity.
func kvSecret(name string, vaultUri string, identityId string) object => {
  name: name
  keyVaultUrl: '${vaultUri}secrets/${name}'
  identity: identityId
}

var registries = useRegistry ? [{ server: containerRegistryServer, identity: identity.id }] : []

// ─── Container Apps environment ────────────────────────────────────────
resource cae 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: envName
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logs.properties.customerId
        sharedKey: logs.listKeys().primarySharedKey
      }
    }
    workloadProfiles: [
      {
        name: 'Consumption'
        workloadProfileType: 'Consumption'
      }
    ]
  }
}

// ACA's default hostname is <app>.<env default domain>, so ORIGIN is known
// before the app exists. Magic links are built from ORIGIN, never from Host,
// so it only moves to the custom domain once that serves valid TLS.
var appOrigin = domainTls ? 'https://${customFqdns[0]}' : 'https://${appName}.${cae.properties.defaultDomain}'

// A managed certificate needs the hostname already on the app, and the app
// can only bind TLS to an issued certificate, so the domain comes up over
// two deploys: hostnames + certificate requests, then the SNI bindings.
var appCustomDomains = !bindDomain
  ? []
  : map(customFqdns, fqdn => domainTls
      ? {
          name: fqdn
          bindingType: 'SniEnabled'
          certificateId: '${cae.id}/managedCertificates/${prefix}-${replace(fqdn, '.', '-')}'
        }
      : { name: fqdn, bindingType: 'Disabled' })

// Container Apps rejects empty secret values, so optional secrets are only
// declared (and referenced) when supplied.
// Same value as kv.properties.vaultUri, but known without a runtime reference,
// so it can be used inside the map() lambdas below.
var vaultUri = 'https://${keyVaultName}${environment().suffixes.keyvaultDns}/'
var coreSecrets = [
  kvSecret('auth-secret', vaultUri, identity.id)
  kvSecret('storage-key', vaultUri, identity.id)
]
// Key Vault secret → env var. Stripe price ids aren't secret, but keeping them
// beside the key stops a live key being paired with test-mode prices.
// STRIPE_PRICE_ID is the legacy name for the Grower monthly price.
var passThroughEnv = [
  { secret: 'stripe-secret-key', env: 'STRIPE_SECRET_KEY' }
  { secret: 'stripe-webhook-secret', env: 'STRIPE_WEBHOOK_SECRET' }
  { secret: 'stripe-price-grower-monthly', env: 'STRIPE_PRICE_GROWER_MONTHLY' }
  { secret: 'stripe-price-grower-monthly', env: 'STRIPE_PRICE_ID' }
  { secret: 'stripe-price-grower-annual', env: 'STRIPE_PRICE_GROWER_ANNUAL' }
  { secret: 'stripe-price-farm-monthly', env: 'STRIPE_PRICE_FARM_MONTHLY' }
  { secret: 'stripe-price-farm-annual', env: 'STRIPE_PRICE_FARM_ANNUAL' }
  { secret: 'pingram-webhook-secret', env: 'PINGRAM_WEBHOOK_SECRET' }
]
var passThrough = filter(
  passThroughEnv,
  e => contains(presentSecrets, e.secret) && (hasPingramKey || !startsWith(e.secret, 'pingram-'))
)
var passThroughSecretNames = union(map(passThrough, e => e.secret), [])
var optionalSecrets = concat(
  hasPingramKey ? [kvSecret('pingram-api-key', vaultUri, identity.id)] : [],
  !hasPingramKey && hasPostmarkToken ? [kvSecret('postmark-token', vaultUri, identity.id)] : [],
  hasAnthropicKey ? [kvSecret('anthropic-api-key', vaultUri, identity.id)] : [],
  hasPushTickSecret ? [kvSecret('push-tick-secret', vaultUri, identity.id)] : [],
  hasVapidKeys
    ? [
        kvSecret('vapid-public-key', vaultUri, identity.id)
        kvSecret('vapid-private-key', vaultUri, identity.id)
      ]
    : [],
  map(passThroughSecretNames, n => kvSecret(n, vaultUri, identity.id))
)
var optionalEnv = concat(
  hasPingramKey
    ? [
        { name: 'EMAIL_TRANSPORT', value: 'pingram' }
        { name: 'SMS_TRANSPORT', value: 'pingram' }
        { name: 'PINGRAM_API_KEY', secretRef: 'pingram-api-key' }
      ]
    : hasPostmarkToken
        ? [
            { name: 'EMAIL_TRANSPORT', value: 'postmark' }
            { name: 'POSTMARK_TOKEN', secretRef: 'postmark-token' }
          ]
        : [{ name: 'EMAIL_TRANSPORT', value: 'stdout' }],
  empty(emailFrom) ? [] : [{ name: 'EMAIL_FROM', value: emailFrom }],
  hasAnthropicKey ? [{ name: 'ANTHROPIC_API_KEY', secretRef: 'anthropic-api-key' }] : [],
  hasPushTickSecret ? [{ name: 'PUSH_TICK_SECRET', secretRef: 'push-tick-secret' }] : [],
  hasVapidKeys
    ? [
        { name: 'VAPID_PUBLIC_KEY', secretRef: 'vapid-public-key' }
        { name: 'VAPID_PRIVATE_KEY', secretRef: 'vapid-private-key' }
      ]
    : [],
  hasVapidKeys && !empty(vapidSubject) ? [{ name: 'VAPID_SUBJECT', value: vapidSubject }] : [],
  map(passThrough, e => { name: e.env, secretRef: e.secret }),
  empty(aiGlobalMonthlyUsdCap) ? [] : [{ name: 'AI_GLOBAL_MONTHLY_USD_CAP', value: aiGlobalMonthlyUsdCap }],
  empty(aiFreePoolMonthlyUsd) ? [] : [{ name: 'AI_FREE_POOL_MONTHLY_USD', value: aiFreePoolMonthlyUsd }]
)

// ─── Container App ─────────────────────────────────────────────────────
resource app 'Microsoft.App/containerApps@2024-03-01' = {
  name: appName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: { '${identity.id}': {} }
  }
  dependsOn: [acrPull, kvSecretsUser, storageKeySecret]
  properties: {
    managedEnvironmentId: cae.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      registries: registries
      ingress: {
        external: true
        targetPort: 8080
        transport: 'auto'
        allowInsecure: false
        customDomains: appCustomDomains
      }
      secrets: concat(coreSecrets, optionalSecrets)
    }
    template: {
      containers: [
        {
          name: 'web'
          image: image
          resources: {
            cpu: json('0.5')
            memory: '1Gi'
          }
          env: concat(
            [
              { name: 'NODE_ENV', value: 'production' }
              { name: 'HOST', value: '0.0.0.0' }
              { name: 'PORT', value: '8080' }
              { name: 'DATABASE_URL', value: 'file:/data/cropcard.db' }
              { name: 'AUTH_SECRET', secretRef: 'auth-secret' }
              { name: 'AUTH_MODE', value: authMode }
              { name: 'ORIGIN', value: appOrigin }
              { name: 'REDIRECT_HOSTS', value: domainTls ? join(skip(customFqdns, 1), ',') : '' }
              { name: 'ADDRESS_HEADER', value: 'X-Forwarded-For' }
              { name: 'XFF_DEPTH', value: '1' }
              { name: 'AZURE_STORAGE_ACCOUNT', value: storage.name }
              { name: 'AZURE_STORAGE_KEY', secretRef: 'storage-key' }
              { name: 'AZURE_BLOB_CONTAINER', value: blobContainerName }
              // Deploy handoff fence (infra/entrypoint.sh, docs/ops/restore-runbook.md).
              { name: 'HANDOFF_FENCE', value: '1' }
            ],
            optionalEnv
          )
          // Startup covers the entrypoint: waiting (up to 75 s) for the old
          // revision to release the database, the restore and migrations.
          // Liveness only begins after it, stays on the static /api/health and
          // tolerates a slow event loop under load (6 x 30 s, 5 s timeout)
          // rather than restarting a busy container. Readiness runs SELECT 1.
          probes: [
            {
              type: 'Startup'
              httpGet: { path: '/api/health', port: 8080 }
              initialDelaySeconds: 10
              periodSeconds: 15
              timeoutSeconds: 5
              failureThreshold: 10
            }
            {
              type: 'Liveness'
              httpGet: { path: '/api/health', port: 8080 }
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 6
            }
            {
              type: 'Readiness'
              httpGet: { path: '/api/health/ready', port: 8080 }
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
            }
          ]
        }
      ]
      // Time for the SIGTERM handoff release (drain, then prove the last WAL
      // frame reached Blob) before the container is killed.
      terminationGracePeriodSeconds: 60
      scale: {
        // Single-writer SQLite — never scale beyond one replica.
        minReplicas: 0
        maxReplicas: 1
      }
    }
  }
}

// ─── Scheduled push wakeup ─────────────────────────────────────────────
// The app scales to zero, so push alerts can't run on an in-process timer.
// Two jobs wake it twice a day: 10:00 and 20:30 UTC are 06:00 / 16:30 EDT
// (frost season) and 05:00 / 15:30 EST (ACA cron has no time zone, and one
// cron can't hold both minutes). The afternoon run catches NWS frost/freeze
// products issued for tonight; the
// morning run covers decon-due, lock-window and calibration alerts. It reuses
// the app image (already in the registry, so no Docker Hub pulls) but only
// runs a node one-liner that POSTs /api/internal/push-tick with the shared
// secret: no volume, no storage key, never touches the database (Invariant 3).
// Retries with backoff cover the cold start; 404 means a secret mismatch and
// fails at once. The crons are pinned by a unit test (push/wakeup.test.ts).
var pushTickScript = '''
const url = process.env.TICK_URL;
const secret = process.env.PUSH_TICK_SECRET;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
(async () => {
  let delay = 5000;
  for (let i = 1; i <= 6; i++) {
    try {
      const r = await fetch(url, {
        method: 'POST',
        headers: { 'x-push-tick-secret': secret },
        signal: AbortSignal.timeout(75000)
      });
      const body = await r.text();
      if (r.status === 200) { console.log(body); process.exit(0); }
      console.log('attempt ' + i + ': HTTP ' + r.status);
      if (r.status === 404) process.exit(1);
    } catch (e) {
      console.log('attempt ' + i + ': ' + e.message);
    }
    await sleep(delay);
    delay = Math.min(delay * 2, 40000);
  }
  process.exit(1);
})();
'''

var pushTickSchedules = [
  { suffix: '', cron: '0 10 * * *' }
  { suffix: '-pm', cron: '30 20 * * *' }
]

resource pushTickJobs 'Microsoft.App/jobs@2024-03-01' = [for s in (hasPushTickSecret ? pushTickSchedules : []): {
  name: '${prefix}-push-tick${s.suffix}'
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: { '${identity.id}': {} }
  }
  dependsOn: [acrPull, kvSecretsUser]
  properties: {
    environmentId: cae.id
    workloadProfileName: 'Consumption'
    configuration: {
      triggerType: 'Schedule'
      replicaTimeout: 600
      replicaRetryLimit: 0
      scheduleTriggerConfig: {
        cronExpression: s.cron
        parallelism: 1
        replicaCompletionCount: 1
      }
      registries: registries
      secrets: [kvSecret('push-tick-secret', vaultUri, identity.id)]
    }
    template: {
      containers: [
        {
          name: 'push-tick'
          image: image
          command: ['node', '-e', pushTickScript]
          resources: {
            cpu: json('0.25')
            memory: '0.5Gi'
          }
          env: [
            { name: 'TICK_URL', value: 'https://${app.properties.configuration.ingress.fqdn}/api/internal/push-tick' }
            { name: 'PUSH_TICK_SECRET', secretRef: 'push-tick-secret' }
          ]
        }
      ]
    }
  }
}]

// ─── Custom domain ─────────────────────────────────────────────────────
// The zone is hosted here so the records track the app's hostname and
// verification ID; the registrar only delegates to its name servers.
resource dnsZone 'Microsoft.Network/dnsZones@2018-05-01' = if (useDomain) {
  name: useDomain ? dnsZoneName : 'unused.invalid'
  location: 'global'
}

resource hostCname 'Microsoft.Network/dnsZones/CNAME@2018-05-01' = [for h in (useDomain ? subdomainHosts : []): {
  parent: dnsZone
  name: h
  properties: {
    TTL: 3600
    CNAMERecord: { cname: app.properties.configuration.ingress.fqdn }
  }
}]

// The apex can't be a CNAME, so it points at the environment's static IP.
resource apexA 'Microsoft.Network/dnsZones/A@2018-05-01' = if (useDomain && hasApex) {
  parent: dnsZone
  name: '@'
  properties: {
    TTL: 3600
    ARecords: [{ ipv4Address: cae.properties.staticIp }]
  }
}

resource hostAsuid 'Microsoft.Network/dnsZones/TXT@2018-05-01' = [for h in (useDomain ? customHosts : []): {
  parent: dnsZone
  name: h == '@' ? 'asuid' : 'asuid.${h}'
  properties: {
    TTL: 3600
    TXTRecords: [{ value: [app.properties.customDomainVerificationId] }]
  }
}]

resource extraTxt 'Microsoft.Network/dnsZones/TXT@2018-05-01' = [for r in items(useDomain ? dnsTxtRecords : {}): {
  parent: dnsZone
  name: r.key
  properties: {
    TTL: 3600
    TXTRecords: [{ value: [r.value] }]
  }
}]

resource extraMx 'Microsoft.Network/dnsZones/MX@2018-05-01' = [for r in items(useDomain ? dnsMxRecords : {}): {
  parent: dnsZone
  name: r.key
  properties: {
    TTL: 3600
    MXRecords: r.value
  }
}]

resource hostCert 'Microsoft.App/managedEnvironments/managedCertificates@2024-03-01' = [for fqdn in (bindDomain ? customFqdns : []): {
  parent: cae
  name: '${prefix}-${replace(fqdn, '.', '-')}'
  location: location
  dependsOn: [app]
  properties: {
    subjectName: fqdn
    domainControlValidation: fqdn == dnsZoneName ? 'HTTP' : 'CNAME'
  }
}]

// ─── Marketplace Container App (Phase 23, optional) ────────────────────
// ClamAV sidecar in the same pod; the marketplace reaches clamd on localhost.
resource marketplaceApp 'Microsoft.App/containerApps@2024-03-01' = if (deployMarketplace) {
  name: marketplaceAppName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: { '${identity.id}': {} }
  }
  dependsOn: [acrPull, kvSecretsUser, storageKeySecret]
  properties: {
    managedEnvironmentId: cae.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      registries: registries
      ingress: {
        external: true
        targetPort: 8080
        transport: 'auto'
        allowInsecure: false
      }
      secrets: concat(
        coreSecrets,
        hasMarketplaceSeed ? [kvSecret('marketplace-seed-credential', vaultUri, identity.id)] : []
      )
    }
    template: {
      containers: [
        {
          name: 'marketplace'
          image: marketplaceImage
          resources: {
            cpu: json('0.5')
            memory: '1Gi'
          }
          env: concat([
            { name: 'NODE_ENV', value: 'production' }
            { name: 'HOST', value: '0.0.0.0' }
            { name: 'PORT', value: '8080' }
            { name: 'DATABASE_URL', value: 'file:/data/marketplace.db' }
            { name: 'DB_PATH', value: '/data/marketplace.db' }
            { name: 'AUTH_SECRET', secretRef: 'auth-secret' }
            { name: 'AZURE_STORAGE_ACCOUNT', value: storage.name }
            { name: 'AZURE_STORAGE_KEY', secretRef: 'storage-key' }
            { name: 'AZURE_BLOB_CONTAINER', value: marketplaceBlobContainerName }
            { name: 'MARKETPLACE_MODE', value: 'internet' }
            { name: 'MARKETPLACE_ADMIN_EMAILS', value: marketplaceAdminEmails }
            { name: 'CLAMAV_HOST', value: 'localhost' }
            { name: 'CLAMAV_PORT', value: '3310' }
          ], hasMarketplaceSeed ? [{ name: 'MARKETPLACE_SEED_CREDENTIAL', secretRef: 'marketplace-seed-credential' }] : [])
          probes: [
            {
              type: 'Liveness'
              httpGet: { path: '/api/v1/health', port: 8080 }
              initialDelaySeconds: 10
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 6
            }
            {
              type: 'Readiness'
              httpGet: { path: '/api/v1/health', port: 8080 }
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
            }
          ]
        }
        {
          // First boot pulls ~150 MB of signatures via freshclam.
          name: 'clamav'
          image: 'clamav/clamav:stable'
          resources: {
            cpu: json('0.5')
            memory: '2Gi'
          }
          env: [
            { name: 'CLAMAV_NO_FRESHCLAMD', value: 'false' }
          ]
        }
      ]
      scale: {
        minReplicas: 0
        maxReplicas: 1
      }
    }
  }
}

// ─── Alerts ────────────────────────────────────────────────────────────
resource alertGroup 'Microsoft.Insights/actionGroups@2023-01-01' = {
  name: '${prefix}-alerts'
  location: 'global'
  properties: {
    groupShortName: 'cropcard'
    enabled: true
    emailReceivers: empty(alertEmail)
      ? []
      : [{ name: 'owner', emailAddress: alertEmail, useCommonAlertSchema: true }]
  }
}

resource alert5xx 'Microsoft.Insights/metricAlerts@2018-03-01' = {
  name: '${appName}-5xx'
  location: 'global'
  properties: {
    description: 'The web app returned more than 5 server errors in 15 minutes.'
    severity: 2
    enabled: true
    scopes: [app.id]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {
          criterionType: 'StaticThresholdCriterion'
          name: 'server-errors'
          metricName: 'Requests'
          metricNamespace: 'Microsoft.App/containerapps'
          dimensions: [{ name: 'statusCodeCategory', operator: 'Include', values: ['5xx'] }]
          operator: 'GreaterThan'
          threshold: 5
          timeAggregation: 'Total'
        }
      ]
    }
    actions: [{ actionGroupId: alertGroup.id }]
  }
}

resource alertRestarts 'Microsoft.Insights/metricAlerts@2018-03-01' = {
  name: '${appName}-restarts'
  location: 'global'
  properties: {
    description: 'A web app container restarted (crash, failed probe, or a restore that refused to start).'
    severity: 2
    enabled: true
    scopes: [app.id]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {
          criterionType: 'StaticThresholdCriterion'
          name: 'restarts'
          metricName: 'RestartCount'
          metricNamespace: 'Microsoft.App/containerapps'
          operator: 'GreaterThan'
          threshold: 0
          timeAggregation: 'Maximum'
        }
      ]
    }
    actions: [{ actionGroupId: alertGroup.id }]
  }
}

var logAlerts = [
  {
    name: 'replication-errors'
    severity: 1
    description: 'Litestream reported an error, or a container refused to start on a bad restore, or a release could not prove its last WAL frame reached Blob.'
    match: 'Log_s contains "level=ERROR" or (Log_s has "litestream" and Log_s has "error") or Log_s has "RESTORE_REFUSED" or Log_s has "RELEASE_UNVERIFIED" or Log_s contains "[entrypoint] FATAL"'
  }
  {
    name: 'handoff-timeout'
    severity: 1
    description: 'A new revision gave up waiting for the old one to release the database; writes the old revision accepted afterwards may be orphaned.'
    match: 'Log_s has "HANDOFF_TIMEOUT"'
  }
]

resource logAlert 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = [for a in logAlerts: {
  name: '${appName}-${a.name}'
  location: location
  properties: {
    description: a.description
    severity: a.severity
    enabled: true
    scopes: [logs.id]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT10M'
    skipQueryValidation: true
    autoMitigate: true
    criteria: {
      allOf: [
        {
          query: 'ContainerAppConsoleLogs_CL | where ContainerAppName_s == "${appName}" | where ${a.match}'
          timeAggregation: 'Count'
          operator: 'GreaterThan'
          threshold: 0
          failingPeriods: { numberOfEvaluationPeriods: 1, minFailingPeriodsToAlert: 1 }
        }
      ]
    }
    actions: { actionGroups: [alertGroup.id] }
  }
}]

output appFqdn string = app.properties.configuration.ingress.fqdn
output appOrigin string = appOrigin
output marketplaceFqdn string = deployMarketplace ? marketplaceApp!.properties.configuration.ingress.fqdn : ''
output customDomainNameServers array = useDomain ? dnsZone!.properties.nameServers : []
output pushTickJobs array = [for (s, i) in (hasPushTickSecret ? pushTickSchedules : []): pushTickJobs[i].name]
output storageAccount string = storage.name
output blobContainer string = blobContainerName
